Repository WildCodeSchool/2022-09-php-orleans-project-papys45, pull requests merged in 2022-11, with the labels that each got.

#79 S01 us06 route table
  .gitignore
  database.sql
  public/assets/css/list-route.css
  public/assets/images/calendar.svg
  public/assets/images/flag.svg
  public/assets/images/mountain.svg
  public/assets/images/pin.svg
  public/assets/images/ravito.svg
  src/Controller/RouteController.php
  src/Model/RouteManager.php
  src/View/Home/index.html.twig
  src/View/List/listRoute.html.twig
  src/routes.php
Labels: Reviewed

#68 S02 us10 members
  database.sql
  public/assets/css/members.css
  public/assets/images/C10.png
  public/assets/images/default.svg
  public/upload/.gitignore
  src/Controller/MemberController.php
  src/Model/MemberManager.php
  src/View/Members/index.html.twig
  src/routes.php
Labels: Reviewed, Corrections done

#78 Fix S01US01_Navbar
  public/assets/css/navbar.css
  public/assets/images/cyclisme.png
  public/assets/images/cyclist.svg
  src/View/_navbar.html.twig
  src/View/layout.html.twig
Labels: Reviewed, Corrections done

#80 S02 us20 admin list members
  public/assets/css/adminMembers.css
  public/upload/.gitignore
  src/Controller/AdminMemberController.php
  src/Model/AdminMemberManager.php
  src/View/Admin/members.html.twig
  src/View/Members/index.html.twig
  src/View/layout.html.twig
  src/routes.php
Labels: Reviewed, Corrections done

#97 FIX_listSortie
  src/View/List/listRoute.html.twig
Labels: Reviewed

#87 fixed link to css forgotten
  src/View/layout.html.twig
Labels: Reviewed

#101 fixed links to pages
  src/View/_navbar.html.twig
Labels: Reviewed

#111 FIX_listSortieCSS
  public/assets/css/list-route.css
Labels: Reviewed

#103 FIX_listeRoute Changed the format of the date & time
  src/View/List/listRoute.html.twig
Labels: Reviewed

#100 S02 us23 admin add members
  database.sql
  public/assets/css/adminMembers.css
  src/Controller/AdminMemberController.php
  src/Controller/MemberController.php
  src/Model/AdminMemberManager.php
  src/Model/MemberManager.php
  src/View/Admin/_formAdminMember.html.twig
  src/View/Admin/membersAdd.html.twig
  src/routes.php
Labels: Reviewed, Corrections done

#114 thanks
  .gitignore
  database.sql
  public/assets/css/adminMembers.css
  public/assets/css/list-route.css
  public/assets/css/members.css
  public/assets/css/navbar.css
  public/assets/css/style.css
  public/assets/images/C10.png
  public/assets/images/calendar.svg
  public/assets/images/cyclisme.png
  public/assets/images/cyclist.svg
  public/assets/images/default.svg
  public/assets/images/flag.svg
  public/assets/images/mountain.svg
  public/assets/images/pin.svg
  public/assets/images/ravito.svg
  public/upload/.gitignore
  src/Controller/AdminMemberController.php
  src/Controller/MemberController.php
  src/Controller/RouteController.php
  src/Model/MemberManager.php
  src/Model/RouteManager.php
  src/View/Admin/_formAdminMember.html.twig
  src/View/Admin/members.html.twig
  src/View/Admin/membersAdd.html.twig
  src/View/Home/index.html.twig
  src/View/List/listRoute.html.twig
  src/View/Members/index.html.twig
  src/View/_navbar.html.twig
  src/View/layout.html.twig
  src/routes.php
Labels: Reviewed

#115 fixed the good route to members page
  src/Controller/MemberController.php
Labels: Reviewed

#118 S02 us27 admin connection
  database.sql
  public/assets/images/error401.svg
  public/index.php
  src/Controller/AbstractController.php
  src/Controller/AdminMemberController.php
  src/Model/UserManager.php
  src/View/Admin/login.html.twig
  src/View/Error/error.html.twig
  src/View/_footer.html.twig
  src/routes.php
Labels: Reviewed

#112 S02 us15 routelist admin
  database.sql
  public/assets/css/adminRoute.css
  src/Controller/AdminRouteController.php
  src/View/AdminRoute/adminRoute.html.twig
  src/routes.php
Labels: Reviewed, Corrections done

#120 fixed admin pages link to admin layout
  src/View/Admin/members.html.twig
  src/View/Admin/membersAdd.html.twig
Labels: Reviewed

#102 S02us12 detail route
  public/assets/css/DetailRoute.css
  public/assets/images/clock.svg
  public/assets/images/distance.svg
  public/assets/images/ravito.svg
  src/Controller/RouteController.php
  src/View/DetailRoute/DetailRoute.html.twig
  src/routes.php
Labels: Reviewed, Corrections done

#119 S02US24_Admin_Actus
  public/assets/css/actuality.css
  src/Controller/AdminActuController.php
  src/View/Admin/Actualities/admin_actuality.html.twig
  src/routes.php
Labels: Reviewed

#94 S02 us22 admin delete members
  src/Controller/AdminMemberController.php
  src/Model/MemberManager.php
  src/View/Admin/adminLogin.html.twig
  src/View/Admin/members.html.twig
  src/routes.php
Labels: Reviewed, Corrections done

#124 fix update role value
  src/Controller/MemberController.php
  src/View/Admin/members.html.twig
  src/View/Members/index.html.twig
Labels: Reviewed, Corrections done

#125 fixed extends layout in admin pages
  src/View/Admin/Actualities/admin_actuality.html.twig
  src/View/AdminRoute/adminRoute.html.twig
Labels: Reviewed

#130 fix pb login
  public/assets/images/admin_logo.svg
  src/routes.php
Labels: Reviewed

#132 FIX-fixed the link for the gpx
  src/View/DetailRoute/DetailRoute.html.twig
Labels: Reviewed

#137 FIX - added the link to add a route for the btn add
  src/View/AdminRoute/adminRoute.html.twig
  src/routes.php
Labels: Reviewed

#138 fix admin navbar
  src/View/_navbarAdmin.html.twig
Labels: Reviewed

#139 FIX- Spacing
  src/View/Admin/AddRouteForm.html.twig
Labels: Reviewed

#140 fixed image member placeholder
  src/View/Admin/_formAdminMember.html.twig
  src/View/Members/index.html.twig
Labels: Reviewed

#127 FIX - Linked the card to the detail page
  src/View/List/listRoute.html.twig
  src/View/_navbar.html.twig
  src/routes.php
Labels: Reviewed, conflict_resolved

#141 FIX- Changed the redirection path when adding a new route
  src/Controller/AddRouteController.php
Labels: Reviewed

#147 fix Poulidor role in database
  database.sql
Labels: Reviewed

#148 fix link switch to admin or visitor when connected
  src/View/_navbar.html.twig
Labels: Reviewed

#149 fix link button to add member
  src/View/Admin/members.html.twig
Labels: Reviewed

#150 fix footer too small in detail route
  src/View/DetailRoute/DetailRoute.html.twig
Labels: Reviewed

#151 fix font size members
  src/View/Members/index.html.twig
Labels: Reviewed

#131 FIXS02US24 - fixed routes names for actualities
  src/View/Admin/Actualities/admin_actuality.html.twig
  src/routes.php
Labels: Reviewed, conflict_resolved

#143 S02 us05 register table
  database.sql
  src/Controller/RouteController.php
  src/Model/RegistrationManager.php
  src/View/DetailRoute/DetailRoute.html.twig
Labels: Reviewed, conflict_resolved

#153 FIX - position of the footer
  src/View/_footer.html.twig
  src/View/baseLayout.html.twig
Labels: Reviewed

#154 fix added president photo
  src/Controller/HomeController.php
  src/Model/MemberManager.php
  src/View/Home/index.html.twig
Labels: Reviewed

#157 FIX S02US24 A couple of fixes in CSS and Bootstrap
  public/assets/css/actuality.css
  src/View/Admin/Actualities/admin_actuality.html.twig
Labels: Reviewed

#155 thanks
  database.sql
  public/assets/css/actuality.css
  src/Controller/HomeController.php
  src/Controller/RouteController.php
  src/Model/MemberManager.php
  src/Model/RegistrationManager.php
  src/View/Admin/Actualities/admin_actuality.html.twig
  src/View/Admin/members.html.twig
  src/View/DetailRoute/DetailRoute.html.twig
  src/View/Home/index.html.twig
  src/View/Members/index.html.twig
  src/View/_footer.html.twig
  src/View/_navbar.html.twig
  src/View/baseLayout.html.twig
  src/routes.php
Labels: Reviewed

#159 fix rename file Detail...twig to detail...twig
  src/View/DetailRoute/detailRoute.html.twig
Labels: Reviewed

#161 fix modify icone inline
  src/View/List/listRoute.html.twig
Labels: Reviewed

#163 fix delete admin link
  src/View/_footer.html.twig
Labels: Reviewed

#156 S02US25 admin add actus
  src/Controller/AdminActuController.php
  src/Model/ActualityManager.php
  src/View/Admin/Actualities/form_actu_add.html.twig
Labels: Reviewed, conflict_resolved

#164 fixed date time format
  src/View/List/listRoute.html.twig
Labels: Reviewed

#158 fix added futur route
  src/View/List/listRoute.html.twig
Labels: Reviewed, conflict_resolved

#160 fix modify upload to uploads
  public/uploads/.gitignore
  src/Controller/AdminMemberController.php
  src/View/Admin/_formAdminMember.html.twig
  src/View/DetailRoute/detailRoute.html.twig
  src/View/Home/index.html.twig
  src/View/Members/index.html.twig
Labels: Reviewed, conflict_resolved

#172 S03US31_Admin_Delete_Actus
  src/Controller/AdminActuController.php
  src/View/Admin/Actualities/admin_actuality.html.twig
  src/View/AdminRoute/adminRoute.html.twig
Labels: Reviewed

#173 FIXS2US24 - Titles are now in bold characters
  public/assets/css/actuality.css
  src/View/Admin/Actualities/admin_actuality.html.twig
Labels: Reviewed

#176 S03 us29 add registration
  public/assets/css/AdminRegistration.css
  src/Controller/AdminRegistrationController.php
  src/Model/RegistrationManager.php
  src/View/Admin/addRegistration.html.twig
  src/View/Admin/registration.html.twig
  src/routes.php
Labels: Reviewed

#178 Modified the header(location)
  src/Controller/AdminActuController.php
Labels: Reviewed

#179 Fix-navbar style
  public/assets/css/navbar.css
  src/View/_navbar.html.twig
Labels: Reviewed

#175 S04 us14 added route photo
  database.sql
  public/assets/css/adminAddRoute.css
  src/Controller/AddRouteController.php
  src/Controller/PhotoController.php
  src/Controller/RouteController.php
  src/Model/PhotoManager.php
  src/Model/RouteManager.php
  src/View/Admin/EditRouteForm.html.twig
  src/View/AdminRoute/adminRoute.html.twig
  src/View/DetailRoute/detailRoute.html.twig
  src/routes.php
Labels: Reviewed

#184 delete function
  src/Controller/AdminRegistrationController.php
  src/Model/RegistrationManager.php
  src/View/Admin/registration.html.twig
  src/routes.php
Labels: Reviewed, conflict_resolved

#188 FIX - added ON DELETE CASCADE in database
  database.sql
Labels: Reviewed

#189 FIX - added id and condition on show photo
  src/Controller/AddRouteController.php
  src/Model/PhotoManager.php
  src/View/Admin/EditRouteForm.html.twig
Labels: Reviewed

#190 FIX - delete photo1 and changed Envoyez to Ajoutez
  src/View/Admin/EditRouteForm.html.twig
Labels: Reviewed

#195 FIX - added on delete cascade
  database.sql
Labels: Reviewed

#194 FIX - Fixed something in the HTML - should be the right font now
  src/Controller/AdminActuController.php
  src/View/Admin/Actualities/form_actu_edit.html.twig
Labels: Reviewed

#192 FIX- margin top to the footer
  src/View/_footer.html.twig
Labels: Reviewed

#191 FIX- navbar style conflict with the detailRoute css
  public/assets/css/navbar.css
  src/View/_navbar.html.twig
Labels: Reviewed

#186 Fix-design detail route
  public/assets/css/DetailRoute.css
  src/View/DetailRoute/detailRoute.html.twig
Labels: Reviewed, conflict_resolved

#199 fix photo member registrered
  src/Controller/RouteController.php
  src/Model/RegistrationManager.php
  src/View/DetailRoute/detailRoute.html.twig
Labels: Reviewed

#200 Fix carousel in order
  database.sql
  src/Controller/HomeController.php
Labels: Reviewed

#193 FIX - Success boxes now work in the Actu forms
  src/Controller/AdminActuController.php
  src/View/Admin/Actualities/form_actu_add.html.twig
  src/View/Admin/Actualities/form_actu_edit.html.twig
  src/routes.php
Labels: Reviewed, conflict_resolved

#187 FIX - added authentification access
  src/Controller/AbstractController.php
  src/Controller/AddRouteController.php
  src/Controller/AdminActuController.php
  src/Controller/AdminMemberController.php
  src/Controller/AdminRegistrationController.php
  src/Controller/AdminRouteController.php
  src/Controller/HomeController.php
  src/routes.php
Labels: Reviewed, conflict_resolved

#197 Fix save text in edit
  src/Controller/AdminActuController.php
  src/Model/ActualityManager.php
  src/View/Admin/Actualities/form_actu_add.html.twig
  src/View/Admin/Actualities/form_actu_edit.html.twig
  src/View/Home/_news.html.twig
Labels: Reviewed, conflict_resolved

#203 Fixed bg size
  public/assets/css/style.css
Labels: Reviewed

#202 FIX the footer
  public/assets/css/adminMembers.css
  public/assets/css/footer.css
  public/assets/css/form.css
  src/View/_footer.html.twig
Labels: Reviewed

#201 fix members registered
  src/Controller/AdminRegistrationController.php
Labels: Reviewed

#206 fix delete message actuality
  src/Controller/AdminActuController.php
  src/View/Admin/Actualities/admin_actuality.html.twig
  src/routes.php
Labels: Reviewed

#205 fix delete message route
  src/Controller/AdminRouteController.php
  src/View/AdminRoute/adminRoute.html.twig
  src/routes.php
Labels: Reviewed

#204 fix difficulty option in select input
  src/Controller/AddRouteController.php
  src/View/Admin/EditRouteForm.html.twig
Labels: Reviewed

#210 Harmonized the title of all pages
  src/View/Admin/Actualities/admin_actuality.html.twig
  src/View/Admin/Actualities/form_actu_add.html.twig
  src/View/Admin/Actualities/form_actu_edit.html.twig
  src/View/Admin/AddRouteForm.html.twig
  src/View/Admin/EditRouteForm.html.twig
  src/View/Admin/addRegistration.html.twig
  src/View/Admin/login.html.twig
  src/View/Admin/members.html.twig
  src/View/Admin/membersAdd.html.twig
  src/View/Admin/membersEdit.html.twig
  src/View/Admin/registration.html.twig
  src/View/AdminRoute/adminRoute.html.twig
  src/View/Form/form.html.twig
  src/View/Members/index.html.twig
Labels: Reviewed

#211 modify return button registration
  src/View/Admin/addRegistration.html.twig
  src/View/Admin/registration.html.twig
Labels: Reviewed

#213 Modified titles in Twig format
  src/View/Admin/Actualities/admin_actuality.html.twig
  src/View/Admin/AddRouteForm.html.twig
  src/View/Admin/EditRouteForm.html.twig
  src/View/Admin/_formAdminMember.html.twig
  src/View/Admin/addRegistration.html.twig
  src/View/Admin/login.html.twig
  src/View/Admin/members.html.twig
  src/View/Admin/registration.html.twig
  src/View/AdminRoute/adminRoute.html.twig
  src/View/Form/form.html.twig
  src/View/Home/index.html.twig
  src/View/List/listRoute.html.twig
  src/View/Members/index.html.twig
Labels: Reviewed

#214 fix delete items
  src/routes.php
Labels: Reviewed

#215 add return button on route form
  src/View/Admin/EditRouteForm.html.twig
Labels: Reviewed

#218 Reduced the weight of the bg
  public/assets/css/style.css
  public/assets/images/BG-Papys45V2.svg
  public/assets/images/BGBGBGBG1.png
Labels: Reviewed

#217 fix role style
  public/assets/css/members.css
  src/View/Members/index.html.twig
Labels: Reviewed

#216 modify actuality btn alignment
  src/View/Admin/Actualities/form_actu_edit.html.twig
Labels: Reviewed, conflict_resolved

#212 fix style add button
  src/View/Admin/registration.html.twig
Labels: Reviewed, conflict_resolved

#221 fix connection to connexion
  src/View/Admin/login.html.twig
Labels: Reviewed

#220 fix footer (thanks to sylvain)
  src/View/baseLayout.html.twig
Labels: Reviewed

#219 Fix nl2br
  src/View/DetailRoute/detailRoute.html.twig
  src/View/Form/form.html.twig
  src/View/Home/_news.html.twig
Labels: Reviewed, conflict_resolved

#223 Removed the content part in the Admin Actus page
  src/View/Admin/Actualities/admin_actuality.html.twig
Labels: Reviewed

#222 RGPD
  src/View/_footer.html.twig
Labels: Reviewed

#224 fix actualites to informations
  src/View/Home/index.html.twig
Labels: Reviewed

#225 Fix actualites to informations - admin & navbar admin edition
  src/View/Admin/Actualities/admin_actuality.html.twig
  src/View/Admin/Actualities/form_actu_add.html.twig
  src/View/Admin/Actualities/form_actu_edit.html.twig
  src/View/_navbarAdmin.html.twig
Labels: Reviewed

#228 Modified the add button
  src/View/Admin/Actualities/form_actu_add.html.twig
Labels: Reviewed

#227 modification of edit route form
  src/View/Admin/EditRouteForm.html.twig
  src/View/Admin/registration.html.twig
Labels: Reviewed

#229 fix label actu
  public/assets/css/actuality.css
Labels: Reviewed

#230 fix_label_add_route
  public/assets/css/adminAddRoute.css
  src/View/Admin/AddRouteForm.html.twig
Labels: Reviewed

#231 Fix sortie design
  public/assets/css/DetailRoute.css
  public/assets/css/list-route.css
  public/assets/images/flag.svg
  public/assets/images/pin.svg
  public/assets/images/ravito.svg
  src/View/DetailRoute/detailRoute.html.twig
  src/View/List/listRoute.html.twig
Labels: Reviewed, conflict_resolved

#255 Fix security route
  src/Controller/AddRouteController.php
Labels: Reviewed

#251 modif title font of admin route edit
  public/assets/css/adminAddRoute.css
  src/View/Admin/EditRouteForm.html.twig
Labels: Reviewed

#254 added form-label and edited spacing of the title
  src/View/Form/form.html.twig
Labels: Reviewed

#256 Edited spacing of the member's title
  src/View/Members/index.html.twig
Labels: Reviewed

#257 fix dateofbirth
  src/Controller/AdminMemberController.php
Labels: Reviewed

#258 Fix edit typos
  src/View/DetailRoute/detailRoute.html.twig
Labels: Reviewed

#259 FIX- footer detail sortie
  public/assets/css/DetailRoute.css
  src/View/DetailRoute/detailRoute.html.twig
Labels: Reviewed, conflict_resolved

#260 FIX- spacing of the ravito txt fixed
  src/View/List/listRoute.html.twig
Labels: Reviewed

#261 fix interger val
  src/Controller/AddRouteController.php
Labels: Reviewed

#263 fix UX/UI route list
  src/View/List/listRoute.html.twig
Labels: Reviewed

#264 fix president speech mobile first
  src/View/Home/index.html.twig
Labels: Reviewed

#265 fix style photo member
  public/assets/css/adminMembers.css
  src/View/Admin/_formAdminMember.html.twig
Labels: Reviewed

#267 Fixed most of the titles margins - should be balanced now
  src/View/DetailRoute/detailRoute.html.twig
  src/View/List/listRoute.html.twig
  src/View/Members/index.html.twig
Labels: Reviewed

#262 fix ravito blank
  src/View/List/listRoute.html.twig
Labels: conflict_resolved

#269 fix description and rapport database
  database.sql
Labels: Reviewed

#270 fix alt photo
  src/View/DetailRoute/detailRoute.html.twig
Labels: Reviewed

#271 modification of position of the president photo
  public/assets/css/speech.css
  src/View/Home/index.html.twig
Labels: Reviewed

#272 FIX - Changed the txt area size
  src/View/DetailRoute/detailRoute.html.twig
Labels: Reviewed, conflict_resolved

#273 fix object dateOfBirth warning
  src/Controller/AdminMemberController.php
Labels: Reviewed

#277 Fix -responsive, display of the txt, photos
  src/View/DetailRoute/detailRoute.html.twig
  src/View/List/listRoute.html.twig
Labels: Reviewed

#276 fix problem actu
  src/Controller/AdminActuController.php
Labels: Reviewed

#275 Fix btn return registration
  src/View/Admin/addRegistration.html.twig
  src/View/Admin/registration.html.twig
Labels: Reviewed

#274 Fix info title
  src/View/Home/index.html.twig
Labels: Reviewed

#279 FIX added favicon
  public/assets/images/cyclistfav.png
  src/View/baseLayout.html.twig
Labels: Reviewed

#280 Thanks ✌️
  database.sql
  public/assets/css/DetailRoute.css
  public/assets/css/actuality.css
  public/assets/css/adminAddRoute.css
  public/assets/css/adminMembers.css
  public/assets/css/list-route.css
  public/assets/css/members.css
  public/assets/css/speech.css
  public/assets/images/cyclistfav.png
  public/assets/images/flag.svg
  public/assets/images/pin.svg
  public/assets/images/ravito.svg
  src/Controller/AddRouteController.php
  src/Controller/AdminActuController.php
  src/Controller/AdminMemberController.php
  src/Controller/RouteController.php
  src/View/Admin/Actualities/admin_actuality.html.twig
  src/View/Admin/Actualities/form_actu_add.html.twig
  src/View/Admin/AddRouteForm.html.twig
  src/View/Admin/EditRouteForm.html.twig
  src/View/Admin/_formAdminMember.html.twig
  src/View/Admin/addRegistration.html.twig
  src/View/Admin/members.html.twig
  src/View/Admin/registration.html.twig
  src/View/AdminRoute/adminRoute.html.twig
  src/View/DetailRoute/detailRoute.html.twig
  src/View/Form/form.html.twig
  src/View/Home/_news.html.twig
  src/View/Home/index.html.twig
  src/View/List/listRoute.html.twig
  src/View/Members/index.html.twig
  src/View/baseLayout.html.twig
Labels: Reviewed
